name: meal_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/Raleway-Regular.ttf
        - asset: assets/Raleway-Bold.ttf
          weight: 700
        - asset: assets/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/RobotoCondensed-Italic.ttf
          style: italic
        - asset: assets/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/RobotoCondensed-Light.ttf
          weight: 300   
  uses-material-design: true
